### ISSUE TITLE
Support protobuf in source and sink

### ISSUE THREAD

**Issue by KedareshwarChaudhari** [siddhi-io/siddhi-io-nats#23]
**Description:**
Currently, the nats extension for siddhi only supports **String.class** [Line in code](https://github.com/siddhi-io/siddhi-io-nats/blob/95cf55288256be92be73770a73bb8a2712b5541e/component/src/main/java/io/siddhi/extension/io/nats/sink/NATSSink.java#L121), unlike gRPC extension which supports **String.class** and **GeneratedMessageV3.class** [Line in code](https://github.com/siddhi-io/siddhi-io-grpc/blob/bc7a80d644785eef42b7353db6848b7678b8e22c/component/src/main/java/io/siddhi/extension/io/grpc/sink/GrpcServiceResponseSink.java#L122). Since nats and nats-streaming both support protobuf messages as payload, this extension throws an exception when trying to send protobuf messages to siddhi via nats, like: 

> @source(type='nats', destination='channel1',@map(type='protobuf', class='com.example.InputStream'))
define stream inputStream (timeStamp long, data int)

Exception:

>ERROR {io.siddhi.distribution.core.internal.ServiceComponent} - Exception occurred when deploying the Siddhi AppTEST.siddhi io.siddhi.distribution.core.internal.exception.SiddhiAppDeploymentException: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'TEST' @ Line: 6. Position: 110, near '@source(type='nats', destination='channel1',@map(type='protobuf', class='com.example.InputStream'))'. At stream 'inputStream', source 'nats' produces incompatible '[class java.lang.String, interface java.util.Map]' classes, while it's source mapper 'protobuf' can only consume '[class com.google.protobuf.GeneratedMessageV3]' classes.

>Caused by: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'TEST' @ Line: 6. Position: 110, near '@source(type='nats', destination='channel1',@map(type='protobuf', class='com.example.InputStream'))'. At stream 'inputStream', source 'nats' produces incompatible '[class java.lang.String, interface java.util.Map]' classes, while it's source mapper 'protobuf' can only consume '[class com.google.protobuf.GeneratedMessageV3]' classes.
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.validateSourceMapperCompatibility(DefinitionParserHelper.java:422)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:357)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:114)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:373)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:229)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:66)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:76)
	at io.siddhi.distribution.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:69)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:92)
	... 55 more

**Suggested Labels:**
type/improvement

**Suggested Assignees:**
@pcnfernando 

**Affected Product Version:**
Siddhi v5.1.0
siddhi-io-nats v 2.0.6 extension

**OS, DB, other environment details and versions:**
Ubuntu 18.04 LTS
siddhi-runner v0.1.0
JDK 1.8.0-openjdk-amd64

**Steps to reproduce:**
Run TEST.siddhi using: 

**TEST.siddhi**
>@App:name("TEST")
@App:description("Test implementation for Nats and Protobuf in siddhi")
@info(name='Input stream from Nats + Protobuf publisher')
@source(type='nats', destination='channel1',@map(type='protobuf', class='com.example.InputStream'))
define stream inputStream (timeStamp long, data int)

**InputStream.proto**
>syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.example";
message InputStream {
  uint64 timeStamp = 1;
  uint32 data = 2;
}

1. Generate Java sources from the InputStream.proto file

> protoc InputStream.proto --java_out=./java-sources/

2. Compile Java Sources to Java Classes

> javac -cp ".:/home/$USER/siddhi-runner-0.1.0/bin/bootstrap/protobuf-java-3.9.1.jar" ./java-sources/com/example/* -d ./java-classes/

Note: protobuf-java-3.9.1.jar is passed to javac classpath for java source files to be compiled.

3. Create jar file from java-classes

>jar cvf com.example.jar -C java-classes .

4. Copy the generated jar file to the siddhi runner classpath, I was not able to load from /jars, so I copied to siddhi-runner-0.1.0/bin/bootstrap/com.example.jar (This is not the recommended way, maybe a separate issue)

5. Run siddhi:

> ./siddhi-runner-0.1.0/bin/runner.sh -Dapps=/path/to/TEST.siddhi

Will provide more details if needed.

**Related Issues:**

**Comment by rushilV** [comment]
Hi when can we expect this siddhi-io-nats with protobuf to release any specific release date

**Comment by rushilV** [comment]
@BuddhiWathsala  when can we expect this feature(siddhi-io-nats with protobuf) to complete any specific release date

**Comment by BuddhiWathsala** [comment]
@rushilV we have found the issue and we are fixing that. In the worst case, we can release it next week.

If I give more details about this, this has to fix that in both `siddhi-map-protobuf` and `siddhi-io-nats`. We are trying to develop that protobuf compatibility on those sides.

**Comment by BuddhiWathsala** [comment]
@KedareshwarChaudhari and @rushilV, the NATS extension and protobuf extension have been released with protobuf communication support. Please test your use cases and let us know about the feature.

**Comment by rushilV** [comment]
@BuddhiWathsala Thanks for the support

**Comment by rushilV** [comment]
@BuddhiWathsala am using "siddhi-tooling-0.1.0" after replacing the siddhi-io-nats and siddhi-map-proobuf in lib folder where all the supporting jar files are maintaining am getting exception also in the code its showing an error "No extension exist for source: Nats"
Attaching the screen shots of the same
![siddhi-nats-exception](https://user-images.githubusercontent.com/55076760/68100644-11283f80-feef-11e9-8f6b-f0635a3c0186.png)
![siddhi-nats-no-extension](https://user-images.githubusercontent.com/55076760/68100645-11c0d600-feef-11e9-89e7-f7ecf97698f2.png)

**Comment by BuddhiWathsala** [comment]
First of all, the thing is the Siddhi tooling 0.1.0 is a minor release and I would recommend using the latest v5.1.0 pack if you do not have any specific reason to use that older version.

Second thing is that according to the stack trace, the issue might be that the tooling pack unable to find the siddhi-io-nats JAR. Which means the NATS jar you put might not be recognizable. Did you correctly replace the new JAR from the previous one?. That means you should rename the new one as the previous JAR name and put it into the same `<SIDDHI-TOOLING-HOME>/lib` directory.

**Comment by rushilV** [comment]
@BuddhiWathsala  thanks, by using siddhi-tooling 5.1.0 those exception and nats source extension not available error are not coming anymore, am using siddhi-io-nats and siddhi-map-protobuf with latest release

**Comment by olsharpe** [comment]
Hi @BuddhiWathsala, not sure if I'm missing something but struggling to get this to work using autogen class `io.siddhi.extension.map.protobuf.autogenerated.Request`

I am running the latest 5.1.2 for both runner and tooling. With the following dependices
- java-nats-streaming-2.2.3
- protobuf-java-3.9.1
- jnats-2.6.5
- siddhi-io-nats-2.0.10
- siddhi-map-protobuf_1.0.4

My test app looks like

```
@App:name("EMSStream")

@App:description("App consumes events from NATS as a protobuf message of SenML format and inserts the events into EMSStream")
/*
Sample message
 {"n":"temperature1","u":"Cel","v":13.6,"bt":1.5782427e+09},{"n":"batteryLevel","u":"V","v":5},{"n":"signalStrength","u":"%EL","v":72}
*/

@info(name='Input stream from Nats + Protobuf publisher')
@source(type='nats',cluster.id='test-cluster', bootstrap.servers='nats://nats:4222', @map(type='protobuf', class='io.siddhi.extension.map.protobuf.autogenerated.Request'))
define stream InputStream (channel string, subtopic string, publisher string, protocol string, contentType string);

@sink(type='log') 
define stream OutputStream (channel string, publisher string);

@info(name='passThrough')
from InputStream
select *
insert into OutputStream;
```

Error
```
[2020-01-05 21:16:09,458] ERROR {io.siddhi.distribution.editor.core.internal.DebugRuntime} - Siddhi App 'EMSStream' is in faulty state. io.siddhi.core.exception.SiddhiAppCreationException: Error on 'EMSStream' @ Line: 11. Position: 171, near '@source(type='nats',cluster.id='test-cluster', bootstrap.servers='nats://nats:4222', @map(type='protobuf', class='io.siddhi.extension.map.protobuf.autogenerated.Request'))'. EMSStream:InputStream: Invalid class name provided in the 'class' parameter, provided class name: io.siddhi.extension.map.protobuf.autogenerated.Request,io.siddhi.extension.map.protobuf.autogenerated.Request cannot be found by siddhi-map-protobuf_1.0.4
```

No sure if you have any ideas how I can resolve this

**Comment by BuddhiWathsala** [comment]
This error indicates that the Siddhi runtime couldn’t find the protobuf JAR that you generated.

@olsharpe, have you put your generated protobuf JAR into `<SIDDHI_HOME>/jars` directory and restart the server?

**Comment by olsharpe** [comment]
@BuddhiWathsala aah ok, I forgot to add them to tooling. Seems to work now. Thanks for support

**Comment by BuddhiWathsala** [comment]
@olsharpe if you need further clarifications please refer to [our slack channel here](https://siddhi.io/community/#community-collaboration).

**Comment by javard** [comment]
Using siddhi-tooling-5.1.0, I've faced a similar error but using tcp as a source. :

`source 'tcp' produces incompatible '[class [B]' classes, while it's source mapper 'protobuf' can only consume '[class com.google.protobuf.GeneratedMessageV3]' classes`
