### ISSUE TITLE
Siddhi support for NATS

### ISSUE THREAD

**Issue by rushilV** [siddhi-io/siddhi-io-nats#33]
Hi,
Currently am using siddhi-runner-5.1.0 in linux environment with NATS-streaming.
The problem is NATS-streaming is adding the huge delay between the message publish almost   3-4 ms and my application processing 991 data points and its adding more over-head.
So can you please provide a support for NATS in siddhi instead of NATS-Streaming.

**Comment by suhothayan** [comment]
Thanks for reporting we'll work on this.

**Comment by BuddhiWathsala** [comment]
I think we can't totally replace NATS instead of NATS streaming because NATS streaming has more extended features. We need to have some design mechanism that support both NATS and NATS streaming. Also, we need to introduce a way to switch between NATS and NATS streaming.

**Comment by rushilV** [comment]
@BuddhiWathsala any updates when NATS support is coming for siddhi

**Comment by BuddhiWathsala** [comment]
@rushilV we almost completed the implementation and we are currently in the testing phase. This can be released probably this week. In the worst case, it will be next week.
